#!/bin/bash
#SBATCH -A cc3uv3p # 2017 XSEDE Applications of Parallel Computing Course Allocation
#SBATCH -J auto-particle-mpi16
#SBATCH -o auto-particle-mpi16.stdout
#SBATCH -n 16         
#SBATCH -p RM
#SBATCH -t 00:10:00     
#SBATCH -N 1        

rm mpi_sum.txt
module load mpi/gcc_mvapich
srun -n 1 ./mpi -n 500 -o mpi_sum.txt
srun -n 2 ./mpi -n 500 -o mpi_sum.txt
srun -n 4 ./mpi -n 500 -o mpi_sum.txt
srun -n 8 ./mpi -n 500 -o mpi_sum.txt
srun -n 16 ./mpi -n 500 -o mpi_sum.txt
srun -n 2 ./mpi -n 1000 -o mpi_sum.txt
srun -n 4 ./mpi -n 2000 -o mpi_sum.txt
srun -n 8 ./mpi -n 4000 -o mpi_sum.txt
srun -n 16 ./mpi -n 8000 -o mpi_sum.txt
./autograder -v mpi -s mpi_sum.txt
