#!/bin/bash
#SBATCH -A cc3uv3p # 2017 XSEDE Applications of Parallel Computing Course Allocation
#SBATCH -J particle-mpi16
#SBATCH -o particle-mpi16.stdout
#SBATCH -N 1 
#SBATCH -n 1         
#SBATCH -p RM
#SBATCH -t 00:10:00
module load mpi/gcc_mvapich
rm mpi_sum.txt
srun -n 2 ./mpi -n 500 -no -s mpi_sum.txt